/** Traditional Juz/Para names, taken from each Juz's opening words (same in Urdu Mushafs, written in Arabic script). */
export const QURAN_PARA_NAMES: Record<number, { arabic: string; english: string }> = {
  1: { arabic: "الٓمٓ", english: "Alif Lam Meem" },
  2: { arabic: "سَيَقُولُ", english: "Sayaqul" },
  3: { arabic: "تِلْكَ الرُّسُلُ", english: "Tilka'r-Rusul" },
  4: { arabic: "لَنْ تَنَالُوا۟", english: "Lan Tana Lu" },
  5: { arabic: "وَالْمُحْصَنَاتُ", english: "Wal-Muhsanat" },
  6: { arabic: "لَا يُحِبُّ اللَّهُ", english: "La Yuhibbullah" },
  7: { arabic: "وَإِذَا سَمِعُوا۟", english: "Wa Iza Sami'u" },
  8: { arabic: "وَلَوْ أَنَّنَا", english: "Wa Lau Annana" },
  9: { arabic: "قَالَ الْمَلَأُ", english: "Qalal Mala'u" },
  10: { arabic: "وَاعْلَمُوا۟", english: "Wa A'lamu" },
  11: { arabic: "يَعْتَذِرُونَ", english: "Ya'tazirun" },
  12: { arabic: "وَمَا مِن دَابَّةٍ", english: "Wa Mamin Dabbah" },
  13: { arabic: "وَمَا أُبَرِّئُ", english: "Wa Ma Ubarri'u" },
  14: { arabic: "رُبَمَا", english: "Rubama" },
  15: { arabic: "سُبْحَانَ الَّذِي", english: "Subhanal-lazi" },
  16: { arabic: "قَالَ أَلَمْ", english: "Qal Alam" },
  17: { arabic: "ٱقْتَرَبَ", english: "Aqtaraba" },
  18: { arabic: "قَدْ أَفْلَحَ", english: "Qad Aflaha" },
  19: { arabic: "وَقَالَ الَّذِينَ", english: "Wa Qalallazina" },
  20: { arabic: "أَمَّنْ خَلَقَ", english: "Amman Khalaq" },
  21: { arabic: "ٱتْلُ مَا أُوحِيَ", english: "Utlu Ma Uhiya" },
  22: { arabic: "وَمَن يَقْنُتْ", english: "Wa Man Yaqnut" },
  23: { arabic: "وَمَا لِيَ", english: "Wa Mali" },
  24: { arabic: "فَمَنْ أَظْلَمُ", english: "Faman Azlam" },
  25: { arabic: "إِلَيْهِ يُرَدُّ", english: "Ilayhi Yuraddu" },
  26: { arabic: "حم", english: "Ha Meem" },
  27: { arabic: "قَالَ فَمَا خَطْبُكُمْ", english: "Qala Fama Khatbukum" },
  28: { arabic: "قَدْ سَمِعَ اللَّهُ", english: "Qad Sami Allah" },
  29: { arabic: "تَبَارَكَ الَّذِي", english: "Tabarakallazi" },
  30: { arabic: "عَمَّ", english: "Amma" },
};
